### ISSUE TITLE
JSSCP Priority 1 (P1) ETL Migration Reports

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/calcutta-kids#105]
I have created this JSSCP 2023_Master Report sheet which consist of all the reports (including Line-List reports) and have prioritised it as P1 and P2. Below are the P1 ETL Migration Reports which are Not Completed as of today. 
Whoever is working on it, kindly update the status as Completed in the Report To ETL sheet:

- [ ] Antenatal services during pregnancy (Program Name: MCH)
- [ ] Disease status fasting (Program Name: Diabetes)
- [ ] Patient enrolled with existing complications (Program: Diabetes)
- [ ] Patients with any new complications (Program: Diabetes)
- [ ] No of patients enrolled with type of disease (Program: Epilepsy)
- [ ] Patients with control over seizures ((Program: Epilepsy)
- [ ] Disease status of patients on amolodipine (Program: Hypertension)
- [ ] Hypertension disease status (Program: Hypertension)
- [ ] Patients enrolled with any complications (Program: Hypertension)
- [ ] Patients on various medicines (Program: Hypertension)
- [ ] Patients with any new complications (Program: Hypertension)
- [ ] Patients diagnosed with different types of TB (Program: TB)
- [ ] Patients diagnosed with extrapulmonary TB with different types (Program: TB)
- [ ] Patients who are on different phases of treatment with any side effects (Program: TB)
- [ ] TB family screening (Program: TB)
- [ ] TB patients with any new comorbidity (Program: TB)
- [ ] Line list for EDD (Program/Report Type: Line List For EDD)
- [ ] All Children (Program: Phulwari)
- [ ] Monthly Data of Weight and Height (Program: Phulwari)
- [ ] New Children enrolled in Phulwari in a month (Program: Phulwari)
- [ ] Line list for EDD (Program/Report Type: Independent Linelist)

Kindly Update "Completed" status here: https://docs.google.com/spreadsheets/d/15U3mOkcVjHhXlr318uj8DRQNzC6mBOTf-GEPf9SLfTM/edit#gid=431825339

Ref Link (JSSCP 2023_Master Report Sheet): https://docs.google.com/spreadsheets/d/110abTQ-685LlptvntVb7DjQTSdh9vzCdLgtMH08MFmY/edit#gid=406344359
